const std = @import("std");
const sdl = @import("clibs.zig").sdl;

pub const Event = enum {
    KeyDown,
    KeyUp,
    Quit,
    WindowMaximized,
    WindowMinimized,
    WindowResized,
    MouseWheel,
    MouseMotion,

    pub fn from(event: sdl.Event) error{NotRegistered}!Event {
        return switch (event.type) {
            sdl.EVENT_KEY_DOWN => Event.KeyDown,
            sdl.EVENT_KEY_UP => Event.KeyUp,
            sdl.EVENT_QUIT => Event.Quit,
            sdl.EVENT_WINDOW_MAXIMIZED => Event.WindowMaximized,
            sdl.EVENT_WINDOW_MINIMIZED => Event.WindowMinimized,
            sdl.EVENT_WINDOW_RESIZED => Event.WindowResized,
            sdl.EVENT_MOUSE_WHEEL => Event.MouseWheel,
            sdl.EVENT_MOUSE_MOTION => Event.MouseMotion,
            else => return error.NotRegistered,
        };
    }
};

pub const KeyCode = enum {
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    LShift,
    RShift,
    pub fn from(key: sdl.Keycode) error{NotRegistered}!@This() {
        return switch (key) {
            sdl.K_0 => .Num0,
            sdl.K_1 => .Num1,
            sdl.K_2 => .Num2,
            sdl.K_3 => .Num3,
            sdl.K_4 => .Num4,
            sdl.K_5 => .Num5,
            sdl.K_6 => .Num6,
            sdl.K_7 => .Num7,
            sdl.K_8 => .Num8,
            sdl.K_9 => .Num9,
            sdl.K_A => .A,
            sdl.K_B => .B,
            sdl.K_C => .C,
            sdl.K_D => .D,
            sdl.K_E => .E,
            sdl.K_F => .F,
            sdl.K_G => .G,
            sdl.K_H => .H,
            sdl.K_I => .I,
            sdl.K_J => .J,
            sdl.K_K => .K,
            sdl.K_L => .L,
            sdl.K_M => .M,
            sdl.K_N => .N,
            sdl.K_O => .O,
            sdl.K_P => .P,
            sdl.K_Q => .Q,
            sdl.K_R => .R,
            sdl.K_S => .S,
            sdl.K_T => .T,
            sdl.K_U => .U,
            sdl.K_V => .V,
            sdl.K_W => .W,
            sdl.K_X => .X,
            sdl.K_Y => .Y,
            sdl.K_Z => .Z,
            sdl.K_ESCAPE => .Escape,
            sdl.K_LSHIFT => .LShift,
            sdl.K_RSHIFT => .RShift,
            else => error.NotRegistered,
        };
    }

    pub fn isShift(self: @This()) bool {
        return self == .LShift or self == .RShift;
    }
};
